export default {
  TODO_ADD: 'TODO_ADD',
  TODO_REMOVE: 'TODO_REMOVE',
  TODO_UPDATE: 'TODO_UPDATE',
  TODO_TOGGLE: 'TODO_TOGGLE',
  TODO_SET_ALL_STATUS: 'TODO_SET_ALL_STATUS',
  SHOW_ALL: 'SHOW_ALL',
  SHOW_ACTIVE: 'SHOW_ACTIVE',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  TODO_CLEAR_COMPLETED: 'TODO_CLEAR_COMPLETED',
  USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
  USER_LOGOUT: 'USER_LOGOUT',
}
